import Head from "next/head";
import React from "react";
import Header from "./Header";

const Layout = ({ children }) => {
  return (
    <div className="">
      <Head>
        <title>Ivhorsnet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LOGO1.ico" />
      </Head>
      <Header />
      {children}
    </div>
  );
};

export default Layout;
