import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LOGO.ico" />
      </Head>
      <div className="">
        <div>hola index</div>
      </div>
    </div>
  );
}
